# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- block:
    - when: anki_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: anki_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

  tags:
    - setup-all
    - setup-anki
    - install-all
    - install-anki

- block:
    - when: not anki_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-anki
