# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Check existence of Excalidraw systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ excalidraw_identifier }}.service"
  register: excalidraw_service_stat

- when: excalidraw_service_stat.stat.exists | bool
  block:
    - name: Ensure Excalidraw systemd service is stopped
      ansible.builtin.service:
        name: "{{ excalidraw_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Excalidraw systemd service doesn't exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ excalidraw_identifier }}.service"
        state: absent

    - name: Ensure Excalidraw base directory doesn't exist
      ansible.builtin.file:
        path: "{{ excalidraw_base_path }}"
        state: absent
