# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Fail if required Anki synchronization server settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - anki_uid
    - anki_gid
    - anki_hostname
    - anki_path_prefix
    - anki_container_network
    - anki_environment_variables_username
    - anki_environment_variables_password

- when: anki_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required Anki synchronization server Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "vars[item] == ''"
      with_items:
        - anki_container_labels_traefik_hostname
        - anki_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `anki_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if anki_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          anki_container_labels_traefik_path_prefix (`{{ anki_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/anki`).
      when: "anki_container_labels_traefik_path_prefix != '/' and anki_container_labels_traefik_path_prefix[-1] == '/'"
